from typing import Any, Protocol

from kafka_di.message.models import DecodedMessage, Message


class Serializer(Protocol):
    def serialize_key(self, value: Any) -> bytes | None: ...
    def serialize_value(self, value: Any) -> bytes | None: ...
    def serialize_headers(self, value: dict[str, Any]) -> dict[str, bytes]: ...
    def deserialize_key(self, value: bytes | None) -> Any: ...
    def deserialize_value(self, value: bytes | None) -> Any: ...
    def deserialize_headers(self, value: dict[str, bytes]) -> dict[str, Any]: ...
    def deserialize(self, message: Message) -> DecodedMessage: ...
